version: '3'
services:
  postgres1:
    build:
      context: ./
    container_name: ph-web
    volumes:
      - /etc/ph-web.ini:/etc/ph-web.ini:ro
    restart: always
    networks:
      - haus
    external_links:
      - caddy-web:o.pup.haus
networks:
  haus:
    external:
      name: haus
